version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  docker: circleci/docker@2.2.0

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12
    resource_class: medium

jobs:
  build-deploy:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install UV
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
      - run:
          name: Create venv and install dependencies
          command: |
            uv sync --all-extras
      - run:
          name: Run tests
          command: |
            uv run pytest -s

      - run:
          name: Create .env file
          command: |
            cat << EOF > .env
            # API Keys
            SERPER_API_KEY=${SERPER_API_KEY}
            OPENAI_API_KEY=${OPENAI_API_KEY}

            # AWS Configuration
            AWS_REGION=${AWS_REGION}
            AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}

            # Repository and Image Configuration
            REPOSITORY_NAME=${REPOSITORY_NAME}
            IMAGE_NAME=${IMAGE_NAME}

            # Lambda Configuration
            LAMBDA_FUNCTION_NAME=${LAMBDA_FUNCTION_NAME}
            ROLE_NAME=${ROLE_NAME}
            ROLE_POLICY_NAME=${ROLE_POLICY_NAME}
            EOF

      - run:
          name: Deploy to AWS
          command: |
            chmod +x build_deploy.sh
            ./build_deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - build-deploy:
          context: aws 
